#!/bin/sh
echo $SHELL

{% if yadm.hostname == "carbon" %}
CLASS=laptop
{% else %}
CLASS=other
{% endif %}
{% if yadm.hostname == "moar" %}
CLASS=workstation
{% endif %}

yadm config local.class $CLASS
echo "yadm class:" $(yadm config local.class)
echo ""

if [[ -e /bin/zsh && $SHELL != /bin/zsh ]]; then
  chsh -s /bin/zsh
  echo ""
fi

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init
echo ""

if [[ $EUID -ge 1000 ]]; then
  echo "Updating the yadm repo origin URL"
  yadm remote set-url origin "git@github.com:alteriks/dotfiles.git"
  echo ""
fi

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping neovim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
  echo ""
fi

if [[ -e ~/.config/tmux/plugins/tpm/bin/install_plugins ]]; then
  echo Automatic tpm installation
  ~/.config/tmux/plugins/tpm/bin/install_plugins
  echo ""
fi

if [[ $CLASS != other && $EUID -ge 1000 ]]; then
  mkdir -p $HOME/git
  #TODO: from list git clone/pull
  mkdir -p $HOME/tmp

  source ~/.zshenv
  mkdir -p "$XDG_CACHE_HOME"/zsh
  mkdir -p "$XDG_DATA_HOME"/zsh
  mkdir -p "$XDG_DATA_HOME"/wineprefixes
fi
