#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
echo -e ${RED}$SHELL${NC}

{% if yadm.hostname == "carbon" %}
CLASS=laptop
{% else %}
CLASS=other
{% endif %}
{% if yadm.hostname == "moar" %}
CLASS=workstation
{% endif %}
{% if yadm.hostname == "nebula" %}
CLASS=server
{% endif %}

yadm config local.class $CLASS
echo -e "${GREEN}[+] yadm class:${NC}" $(yadm config local.class)
echo ""

if [[ -e /bin/zsh && $SHELL != /bin/zsh ]]; then
  chsh -s /bin/zsh
  echo ""
fi


if [[ $EUID -ge 1000 ]]; then
  echo 
  echo -e "${GREEN}[+] Installing packages (pacman)${NC}"
  echo 
  sudo ~/bin/yadm/arch/pacman.sh

  echo 
  echo -e "${GREEN}[+] Installing packages (yay)${NC}"
  echo 
  ~/bin/yadm/arch/user.sh

  echo 
  echo -e "${GREEN}[+] PostInstall as root${NC}"
  echo 
  sudo ~/bin/yadm/arch/root_post.sh
  echo ""
fi

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo -e "${GREEN}[+] Init submodules${NC}"
yadm submodule update --recursive --init
echo ""

if [[ $EUID -ge 1000 ]]; then
  echo -e "${GREEN}[+] Updating the yadm repo origin URL${NC}"
  yadm remote set-url origin "git@github.com:alteriks/dotfiles.git"
  echo ""
fi

if command -v nvim >/dev/null 2>&1; then
  echo -e "${GREEN}[+] Bootstraping neovim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
  echo ""
fi

if [[ -e ~/.config/tmux/plugins/tpm/bin/install_plugins ]]; then
  echo -e "${GREEN}[+] Automatic tpm installation${NC}"
  ~/.config/tmux/plugins/tpm/bin/install_plugins
  echo ""
fi

if [[ $CLASS != other ]]; then
  echo -e "${GREEN}Mkdir${NC}"
  mkdir -p $HOME/git
  mkdir -p $HOME/tmp

  source ~/.profile
  mkdir -p "$XDG_CACHE_HOME"/zsh
  mkdir -p "$XDG_DATA_HOME"/zsh
  mkdir -p "$XDG_CACHE_HOME"/nvim
  mkdir -p "$XDG_DATA_HOME"/wineprefixes
fi

if [[ $CLASS != other && $EUID -ge 1000 ]]; then
  echo
  #TODO: from list git clone/pull
fi
