#!/bin/bash

set -eo pipefail

: "${BOOTSTRAP_QUICK:=0}"
echo BOOTSTRAP_QUICK="$BOOTSTRAP_QUICK"
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
echo -e "${RED}$SHELL${NC}"

echo -e "${GREEN}Mkdir${NC}"
mkdir -vp "$HOME/git"
mkdir -vp "$HOME/tmp"

source "$HOME/.profile"
mkdir -vp "$XDG_CACHE_HOME"/zsh
mkdir -vp "$XDG_DATA_HOME"/zsh
mkdir -vp "$XDG_CACHE_HOME"/nvim
