#!/bin/env bash
#########################
# Switch lsd theme mode
#########################

cat <<EOF >~/.config/lsd/colors.yaml
---
# Auto-generated by darkman light-mode.d/lsd.sh
user: 230
group: 187
EOF
