---
date: relative
blocks:
  - permission
  - links
  - user
  - group
  - size
  - date
  - name
  # == Icons ==
icons:
  when: auto
  theme: unicode
  separator: " "
sorting:
  dir-grouping: first

color:
  # When to colorize the output.
  # When "classic" is set, this is set to "never".
  # Possible values: never, auto, always
  when: auto
  # How to colorize the output.
  # When "classic" is set, this is set to "no-color".
  # Possible values: default, custom
  # When "custom" is set, lsd will look in the config directory for `colors.yaml`.
  theme: custom
