#!/bin/sh

# YADM_VERSION=$( yadm --version | sed 's/[^0-9.]//g' )
# yadm 2.25 GIT_DIR=~/.config/yadm/repo.git
# yadm 3.1  GIT_DIR=~/.local/share/yadm/repo.git
# printf '%s\n%s' "3" "$YADM_VERSION" | sort -VC && YADM_DIR=~/.local/share/yadm/repo.git || YADM_DIR=~/.config/yadm/repo.git

if [ "$YADM_HOOK_REPO" == "$XDG_DATA_HOME/yadm/repo.git" ] && [ "$YADM_HOOK_WORK" == "$HOME" ]; then
  echo tutaj
  YADM_REPO_NAME="yadm"
elif [ "$YADM_HOOK_REPO" == "$XDG_DATA_HOME/yadm/priv.git/repo.git" ] && [ "$YADM_HOOK_WORK" == "$HOME" ]; then
  YADM_REPO_NAME="privyadm"
elif [ "$YADM_HOOK_REPO" == "/etc/yadm/repo.git" ] && [ "$YADM_HOOK_WORK" == "/etc" ]; then
  YADM_REPO_NAME="sysyadm"
else
  echo '[!] "$YADM_HOOK_REPO" or "$YADM_HOOK_WORK" not defined.'
  exit 1
fi

export GIT_STORE_META="$XDG_CONFIG_HOME/yadm/git_store_meta/$YADM_REPO_NAME"
