#!/bin/sh

YADM_VERSION=$( yadm --version | sed 's/[^0-9.]//g' )
GIT_STORE_META=~/.github/git_store_meta

# yadm 2.25 GIT_DIR=~/.config/yadm/repo.git
# yadm 3.1  GIT_DIR=~/.local/share/yadm/repo.git
printf '%s\n%s' "3" "$YADM_VERSION" | sort -VC && YADM_DIR=~/.local/share/yadm/repo.git || YADM_DIR=~/.config/yadm/repo.git

GIT_DIR=$YADM_DIR GIT_WORK_TREE=~/ ~/bin/git-store-meta.pl -t $GIT_STORE_META --update
