#!/bin/env bash
#########################
# Switch lsd theme mode
#########################

cat <<EOF >~/.config/lsd/colors.yaml
---
# Auto-generated by darkman light-mode.d/lsd.sh
user: 68
group: 69
size:
  none: 24
  small: 52
  medium: 160
  large: 124
EOF
